services:
  postgres:
    image: 'postgres:15-alpine'
    environment:
      - 'POSTGRES_DB=University'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432'

  university-app:
    build: .
    container_name: university-schedule-app
    ports:
     - "8080:8080"
    depends_on:
    - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/University
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234